const SocketEvents = {
  CONNECTION: 'connect',
  ONLINE: 'ONLINE',
  USER_ONLINE: 'USER_ONLINE',
  SEND_MESSAGE: 'SENDMESSAGE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  TYPING: 'TYPING',
  NOTIFY_TYPING: 'NOTIFY_TYPING',
  START_CONV: 'START_CONV',
  OUT_GOING_CALL: 'OUT_GOING_CALL',
  DISCONNECT: 'DISCONNECT',
  DISCONNECTED: 'DISCONNECTED',
  JOINROOM: 'JOINROOM',
  LEAVEROOM: 'LEAVEROOM',
  NOTIFY_USER: 'NOTIFY_USER',
  LOGOUT: 'LOGOUT',
}

Object.freeze(SocketEvents)

export default SocketEvents
