export const LOGIN_ENDPOINT = '/api/auth/login'
export const SIGNUP_ENDPOINT = '/api/auth/signup'
export const SIGNUP_ENDPOINT_DOCTOR = '/api/auth/doctor-signup'
export const CLOUDINARY_ENDPOINT =
  'https://api.cloudinary.com/v1_1/nxttech/image/upload' //move to env
export const SET_SUBSCRIPTION_ENDPOINT = '/api/pt/subscribe'
export const GET_SUBSCRIPTION_ENDPOINT = '/api/pt/subscription'
export const CANCEL_SUBSCRIPTION_ENDPOINT = '/api/pt/cancel-subscription'
export const GET_SUB_USER_ENDPOINT = '/api/pt/profile/get-sub-users'
export const ADD_SUB_USER_ENDPOINT = '/api/pt/profile/add-sub-users'
export const REMOVE_SUB_USER_ENDPOINT = '/api/pt/profile/delete-sub-user'
export const UPDATE_USER_PROFILE_ENDPOINT = '/api/pt/profile/update'
export const GET_USER_PROFILE_ENDPOINT = '/api/pt/profile'
export const ADD_NEXT_OF_KIN_ENDPOINT = '/api/contacts/add'
export const GET_NEXT_OF_KIN_ENDPOINT = '/api/contacts'
export const REMOVE_NEXT_OF_KIN_ENDPOINT = '/api/contacts/delete'
export const UPDATE_USER_MEDICAL_ENDPOINT = '/api/pt/basic-medical-info/update'
export const GET_USER_MEDICAL_ENDPOINT = '/api/pt/basic-health-info'
export const FILTER_DOCTOR_BY_SPEC_ENDPOINT = '/api/doc/filter-doc-by-spec'
export const GET_DOCTOR_AVAILABILITY_ENDPOINT = '/api/pt/availability'
export const BOOK_APPOINTMENT_ENDPOINT = '/api/pt/appointment/book'
export const GET_ALL_APPOINTMENT_ENDPOINT = '/api/pt/appointment/all'
export const UPDATE_PASSWORD_ENDPOINT = '/api/auth/update-password'
export const CANCEL_APPOINTMENT_ENDPOINT = '/api/pt/appointment/cancel'
export const GET_USER_ACTIVITY_ENDPOINT = '/api/pt/activity/logs/user'
export const SET_MEDICAL_ILLNESS_ENDPOINT = '/api/pt/diseases/update'
export const GET_MEDICAL_ILLNESS_ENDPOINT = '/api/pt/health-info'
export const SET_PATIENT_PERIOD_INFO_ENDPOINT =
  '/api/pt/profile/add-period-tracker'
export const GET_PATIENT_PERIOD_INFO_ENDPOINT = '/api/pt/period-tracker/next'
export const GET_DOCTORS_PROFILE = '/api/doc/profile'
export const GET_UP_COMMING_APPOINTMENT_ENDPOINT =
  '/api/doc/appointment/upcoming'
export const GET_REQUEST_APPOINTMENT_ALL = '/api/doc/appointment/all-requested'
export const FORGOT_PASSWORD = '/api/auth/forgot-password?email='
export const RESET_PASSWORD = '/api/auth/reset-password'
export const GET_ALL_BANKS = '/api/bank/all'
export const GET_BANK_DETAILS = '/api/bank/details'
export const VERIFY_BANK_DETAILS = '/api/bank/account-number/verify'
export const UPDATE_BANK_DETAILS_ENDPOINT = '/api/bank/details/update'
export const UPDATE_DOCTOR_PROFILE_ENDPOINT = '/api/doc/profile/update'
export const UPDATE_NEXT_OF_KIN_ENDPOINT = '/api/contacts/update'
export const GET_TOTAL_DOCTOR_APPOINTMENTS = '/api/pt/total-doctor-appointments'
export const GET_TOTAL_DOCTOR_CONVERSATIONS =
  '/api/pt/total-doctor-conversations'
export const GET_PRESCRIPTIONS_COUNT = '/api/pt/prescription-count'
export const GET_LAB_REQUESTS = '/api/pt/lab-appointments'
export const GET_ALL_PHARMACY_REQUESTS = '/api/pt/phar-appointments'
export const GET_ALL_PRESCRIRPTIONS = '/api/pt/prescriptions'
export const GET_ALL_DOCTORS = '/api/doc/all-general-practitioner-doctors'
export const GET_TOTAL_LAB_APPOINTMENTS =
  '/api/pt/total-laboratory-appointments'
export const GET_DOCTOR_BY_SEARCH = '/api/doc/search'
export const DELETE_DOCTOR_AVILABILITY_ENDPOINT =
  '/api/doc/remove-availabiliy?doctorAvailabilityId'
export const SET_DOCTOR_AVAILABILITY_ENDPOINT = '/api/doc/availability/update'
export const GET_DOC_AVAILABILITY_ENDPOINT = '/api/doc/availability'
export const SET_DOCTOR_APPOINTMENT_ENDPOINT =
  '/api/doc/appointment/update-status'
export const GET_DOCTOR_ACTIVITY_ENDPOINT = '/api/doc/activity/logs/user'
export const VERIFY_EMAIL_ENDPOINT = '/api/auth/verify-mail'
export const GET_PATIENT_SIGNUP_LOGS_ENDPOINT =
  '/api/admin/activity/logs/signup/pt'
export const SET_FIREBASE_TOKEN_ENDPOINT = '/api/firebase'
export const DELETE_FIREBASE_TOKEN_ENDPOINT = '/api/delete-firebase-token'
export const GET_USERS_DOCTOR = '/api/message/doctors'
export const GET_USERS_PATIENT = '/api/message/patients'
export const CHAT_MESSAGES_ENDPOINT = '/api/message/retrieve'
export const OFFLINE_CHAT_MESSAGES_ENDPOINT =
  '/api/message/offline-messages/count'
export const CLEAN_UP_NOTI_ENDPOINT = '/api/message/offline-messages/cleanup'
export const GET_RESGISTERED_PATIENT_COUNT_ENDPOINT = '/api/admin/register/pt'
export const GET_RESGISTERED_DOCTOR_COUNT_ENDPOINT = '/api/admin/register/doc'
export const GET_RESGISTERED_LABORATORY_COUNT_ENDPOINT =
  '/api/admin/register/lab'
export const GET_RESGISTERED_PHARMACY_COUNT_ENDPOINT =
  '/api/admin/register/pharmacy'
export const GET_RESGISTERED_SUB_ADMIN_COUNT_ENDPOINT =
  '/api/admin/register/sub-admins'
export const GET_DOCTOR_SIGNUP_LOGS_ENDPOINT = '/api/admin/view-signup-requests'
export const GET_DOCTOR_DETAILS_ENDPOINT = '/api/admin/doc-details'
export const SET_DOCTOR_SIGNUP_STATUS_ENDPOINT =
  '/api/admin/accept-reject-doc-signup-req'
export const GET_ADMIN_PROFILE_ENDPOINT = '/api/admin/details'
export const UPDATE_ADMIN_PROFILE_ENDPOINT = '/api/admin/details/update'
export const GET_ADMIN_ACTIVITY_ENDPOINT = '/api/admin/activity/logs/user'
export const GET_AGORA_RTM_TOKEN_ENDPOINT =
  '/api/message/generate-agora-rtm-token'
export const GET_AGORA_RTC_TOKEN_ENDPOINT =
  '/api/message/generate-agora-rtc-token'
