import { ISearchDoctor } from 'interface/doctorSearch'

export const initialDoctorSearch: ISearchDoctor | null = {
  content: [
    {
      id: 0,
      lastName: '',
      firstName: '',
      phoneNumber: '',
      gender: '',
      email: '',
      profilePics: null,
      address: null,
      speciality: '',
      qualification: '',
      bio: null,
      appointmentCost: 0,
      age: 0,
      duration: 0,
      hospital: null,
      location: null,
      dateOfBirth: null,
      curriculumVitae: null,
      validLicense: null,
      validMeansOfIdentification: null,
      experienceYear: 0,
      practiseNumber: '',
      patientInteractionCount: 0,
      freeConsultation: false,
    },
  ],
  pageable: {
    sort: {
      sorted: false,
      empty: true,
      unsorted: true,
    },
    pageNumber: 0,
    pageSize: 10,
    offset: 0,
    paged: true,
    unpaged: false,
  },
  totalPages: 0,
  totalElements: 0,
  last: true,
  first: true,
  sort: {
    sorted: false,
    empty: true,
    unsorted: true,
  },
  size: 10,
  number: 0,
  numberOfElements: 0,
  empty: false,
}
